apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-traefik
  namespace: sample-app
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: sample-app-strip-sample-app-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /sample-app
            pathType: Prefix
            backend:
              service:
                name: sample-app
                port:
                  number: 80
